using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace compiler
{
    class ParseTableBuilder
    {
        public static ParseTable Build()
        {
            var builder = new ParseTableBuilder();

            var table = new ParseTable();
            table.SetActionsTable(builder.CreateActionsTable());
            table.SetGoToTable(builder.CreateGoToTable());
            table.SetProductionsInfoTable(builder.CreateProductionsInfo());
            return table;
        }

        // PARSE ACTIONS DICTIONARY
        public Dictionary<KeyValuePair<int, TokenType>, ParseAction> CreateActionsTable()
        {
            return new Dictionary<KeyValuePair<int, TokenType>, ParseAction>()
{
	{ new KeyValuePair<int, TokenType>(27, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.EQUAL), new ParseAction(ParseActionKind.SHIFT, 95) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.LTE), new ParseAction(ParseActionKind.SHIFT, 96) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.GTE), new ParseAction(ParseActionKind.SHIFT, 97) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.GT), new ParseAction(ParseActionKind.SHIFT, 98) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.LT), new ParseAction(ParseActionKind.SHIFT, 99) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 100) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 100) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 100) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 100) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.AND), new ParseAction(ParseActionKind.SHIFT, 89) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 68) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 66) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 67) },
	{ new KeyValuePair<int, TokenType>(101, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 65) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(85, TokenType.OR), new ParseAction(ParseActionKind.SHIFT, 86) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 63) },
	{ new KeyValuePair<int, TokenType>(90, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 64) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 68) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 66) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 67) },
	{ new KeyValuePair<int, TokenType>(101, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 65) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(57, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(62, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(71, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(57, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(62, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(71, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 50) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.DOT), new ParseAction(ParseActionKind.SHIFT, 54) },
	{ new KeyValuePair<int, TokenType>(70, TokenType.DOT), new ParseAction(ParseActionKind.SHIFT, 54) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.MOD), new ParseAction(ParseActionKind.SHIFT, 41) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.MOD), new ParseAction(ParseActionKind.SHIFT, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.DIV), new ParseAction(ParseActionKind.SHIFT, 42) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.DIV), new ParseAction(ParseActionKind.SHIFT, 42) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.SHIFT, 43) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.SHIFT, 43) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.MINUS), new ParseAction(ParseActionKind.SHIFT, 34) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.MINUS), new ParseAction(ParseActionKind.SHIFT, 34) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.PLUS), new ParseAction(ParseActionKind.SHIFT, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.PLUS), new ParseAction(ParseActionKind.SHIFT, 35) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(34, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 47) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 46) },
	{ new KeyValuePair<int, TokenType>(38, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(41, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 50) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 49) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 48) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(57, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(62, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(71, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(15, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 78) },
	{ new KeyValuePair<int, TokenType>(21, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 78) },
	{ new KeyValuePair<int, TokenType>(26, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 30) },
	{ new KeyValuePair<int, TokenType>(66, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 29) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 28) },
	{ new KeyValuePair<int, TokenType>(69, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 27) },
	{ new KeyValuePair<int, TokenType>(73, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 32) },
	{ new KeyValuePair<int, TokenType>(75, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 78) },
	{ new KeyValuePair<int, TokenType>(77, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 33) },
	{ new KeyValuePair<int, TokenType>(82, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 78) },
	{ new KeyValuePair<int, TokenType>(84, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(73, TokenType.ELSE), new ParseAction(ParseActionKind.SHIFT, 74) },
	{ new KeyValuePair<int, TokenType>(84, TokenType.ELSE), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(70, TokenType.ASSIGNMENT), new ParseAction(ParseActionKind.SHIFT, 71) },
	{ new KeyValuePair<int, TokenType>(15, TokenType.RETURN), new ParseAction(ParseActionKind.SHIFT, 24) },
	{ new KeyValuePair<int, TokenType>(21, TokenType.RETURN), new ParseAction(ParseActionKind.SHIFT, 24) },
	{ new KeyValuePair<int, TokenType>(26, TokenType.RETURN), new ParseAction(ParseActionKind.REDUCE, 30) },
	{ new KeyValuePair<int, TokenType>(66, TokenType.RETURN), new ParseAction(ParseActionKind.REDUCE, 29) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.RETURN), new ParseAction(ParseActionKind.REDUCE, 28) },
	{ new KeyValuePair<int, TokenType>(69, TokenType.RETURN), new ParseAction(ParseActionKind.REDUCE, 27) },
	{ new KeyValuePair<int, TokenType>(73, TokenType.RETURN), new ParseAction(ParseActionKind.REDUCE, 32) },
	{ new KeyValuePair<int, TokenType>(75, TokenType.RETURN), new ParseAction(ParseActionKind.SHIFT, 24) },
	{ new KeyValuePair<int, TokenType>(77, TokenType.RETURN), new ParseAction(ParseActionKind.REDUCE, 33) },
	{ new KeyValuePair<int, TokenType>(82, TokenType.RETURN), new ParseAction(ParseActionKind.SHIFT, 24) },
	{ new KeyValuePair<int, TokenType>(84, TokenType.RETURN), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(15, TokenType.PASS), new ParseAction(ParseActionKind.SHIFT, 18) },
	{ new KeyValuePair<int, TokenType>(75, TokenType.PASS), new ParseAction(ParseActionKind.SHIFT, 18) },
	{ new KeyValuePair<int, TokenType>(82, TokenType.PASS), new ParseAction(ParseActionKind.SHIFT, 18) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.COMMA), new ParseAction(ParseActionKind.SHIFT, 62) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(112, TokenType.COMMA), new ParseAction(ParseActionKind.SHIFT, 113) },
	{ new KeyValuePair<int, TokenType>(116, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 21) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 48) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(57, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 58) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 60) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 57) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 58) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(80, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 81) },
	{ new KeyValuePair<int, TokenType>(85, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 61) },
	{ new KeyValuePair<int, TokenType>(87, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 62) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 63) },
	{ new KeyValuePair<int, TokenType>(90, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 64) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 68) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 66) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 67) },
	{ new KeyValuePair<int, TokenType>(101, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 65) },
	{ new KeyValuePair<int, TokenType>(108, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 109) },
	{ new KeyValuePair<int, TokenType>(110, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 111) },
	{ new KeyValuePair<int, TokenType>(112, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 19) },
	{ new KeyValuePair<int, TokenType>(114, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 20) },
	{ new KeyValuePair<int, TokenType>(116, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 21) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(34, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 47) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 46) },
	{ new KeyValuePair<int, TokenType>(38, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(41, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 50) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 49) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 48) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 57) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 57) },
	{ new KeyValuePair<int, TokenType>(57, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(62, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(70, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 57) },
	{ new KeyValuePair<int, TokenType>(71, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(78, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 79) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(105, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 108) },
	{ new KeyValuePair<int, TokenType>(102, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 11) },
	{ new KeyValuePair<int, TokenType>(103, TokenType.INT), new ParseAction(ParseActionKind.SHIFT, 117) },
	{ new KeyValuePair<int, TokenType>(108, TokenType.INT), new ParseAction(ParseActionKind.SHIFT, 117) },
	{ new KeyValuePair<int, TokenType>(113, TokenType.INT), new ParseAction(ParseActionKind.SHIFT, 117) },
	{ new KeyValuePair<int, TokenType>(120, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(121, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 9) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(102, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 11) },
	{ new KeyValuePair<int, TokenType>(103, TokenType.CHAR), new ParseAction(ParseActionKind.SHIFT, 118) },
	{ new KeyValuePair<int, TokenType>(108, TokenType.CHAR), new ParseAction(ParseActionKind.SHIFT, 118) },
	{ new KeyValuePair<int, TokenType>(113, TokenType.CHAR), new ParseAction(ParseActionKind.SHIFT, 118) },
	{ new KeyValuePair<int, TokenType>(120, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(121, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 9) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(102, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 11) },
	{ new KeyValuePair<int, TokenType>(103, TokenType.BOOL), new ParseAction(ParseActionKind.SHIFT, 119) },
	{ new KeyValuePair<int, TokenType>(108, TokenType.BOOL), new ParseAction(ParseActionKind.SHIFT, 119) },
	{ new KeyValuePair<int, TokenType>(113, TokenType.BOOL), new ParseAction(ParseActionKind.SHIFT, 119) },
	{ new KeyValuePair<int, TokenType>(120, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(121, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 9) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(102, TokenType.STATIC), new ParseAction(ParseActionKind.SHIFT, 120) },
	{ new KeyValuePair<int, TokenType>(121, TokenType.STATIC), new ParseAction(ParseActionKind.REDUCE, 9) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.STATIC), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(7, TokenType.PRIVATE), new ParseAction(ParseActionKind.SHIFT, 121) },
	{ new KeyValuePair<int, TokenType>(10, TokenType.PRIVATE), new ParseAction(ParseActionKind.SHIFT, 121) },
	{ new KeyValuePair<int, TokenType>(12, TokenType.PRIVATE), new ParseAction(ParseActionKind.SHIFT, 121) },
	{ new KeyValuePair<int, TokenType>(17, TokenType.PRIVATE), new ParseAction(ParseActionKind.REDUCE, 15) },
	{ new KeyValuePair<int, TokenType>(106, TokenType.PRIVATE), new ParseAction(ParseActionKind.REDUCE, 7) },
	{ new KeyValuePair<int, TokenType>(7, TokenType.PUBLIC), new ParseAction(ParseActionKind.SHIFT, 122) },
	{ new KeyValuePair<int, TokenType>(10, TokenType.PUBLIC), new ParseAction(ParseActionKind.SHIFT, 122) },
	{ new KeyValuePair<int, TokenType>(12, TokenType.PUBLIC), new ParseAction(ParseActionKind.SHIFT, 122) },
	{ new KeyValuePair<int, TokenType>(17, TokenType.PUBLIC), new ParseAction(ParseActionKind.REDUCE, 15) },
	{ new KeyValuePair<int, TokenType>(106, TokenType.PUBLIC), new ParseAction(ParseActionKind.REDUCE, 7) },
	{ new KeyValuePair<int, TokenType>(18, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 19) },
	{ new KeyValuePair<int, TokenType>(25, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 26) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(65, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 66) },
	{ new KeyValuePair<int, TokenType>(68, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 69) },
	{ new KeyValuePair<int, TokenType>(72, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 31) },
	{ new KeyValuePair<int, TokenType>(105, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 106) },
	{ new KeyValuePair<int, TokenType>(7, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 6) },
	{ new KeyValuePair<int, TokenType>(8, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 9) },
	{ new KeyValuePair<int, TokenType>(10, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 6) },
	{ new KeyValuePair<int, TokenType>(11, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 5) },
	{ new KeyValuePair<int, TokenType>(12, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 6) },
	{ new KeyValuePair<int, TokenType>(13, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 4) },
	{ new KeyValuePair<int, TokenType>(16, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 17) },
	{ new KeyValuePair<int, TokenType>(17, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 15) },
	{ new KeyValuePair<int, TokenType>(19, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 23) },
	{ new KeyValuePair<int, TokenType>(20, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 22) },
	{ new KeyValuePair<int, TokenType>(21, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 26) },
	{ new KeyValuePair<int, TokenType>(22, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 24) },
	{ new KeyValuePair<int, TokenType>(23, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 25) },
	{ new KeyValuePair<int, TokenType>(26, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 30) },
	{ new KeyValuePair<int, TokenType>(66, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 29) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 28) },
	{ new KeyValuePair<int, TokenType>(69, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 27) },
	{ new KeyValuePair<int, TokenType>(73, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 32) },
	{ new KeyValuePair<int, TokenType>(76, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 77) },
	{ new KeyValuePair<int, TokenType>(77, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 33) },
	{ new KeyValuePair<int, TokenType>(83, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 84) },
	{ new KeyValuePair<int, TokenType>(84, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(106, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 7) },
	{ new KeyValuePair<int, TokenType>(5, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 7) },
	{ new KeyValuePair<int, TokenType>(14, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 15) },
	{ new KeyValuePair<int, TokenType>(74, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 75) },
	{ new KeyValuePair<int, TokenType>(81, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 82) },
	{ new KeyValuePair<int, TokenType>(107, TokenType.BLOCK_START), new ParseAction(ParseActionKind.REDUCE, 16) },
	{ new KeyValuePair<int, TokenType>(109, TokenType.BLOCK_START), new ParseAction(ParseActionKind.REDUCE, 18) },
	{ new KeyValuePair<int, TokenType>(111, TokenType.BLOCK_START), new ParseAction(ParseActionKind.REDUCE, 17) },
	{ new KeyValuePair<int, TokenType>(4, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 5) },
	{ new KeyValuePair<int, TokenType>(15, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 70) },
	{ new KeyValuePair<int, TokenType>(21, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 70) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(26, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 30) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 45) },
	{ new KeyValuePair<int, TokenType>(34, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 47) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 46) },
	{ new KeyValuePair<int, TokenType>(38, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 45) },
	{ new KeyValuePair<int, TokenType>(41, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 50) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 49) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 48) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 55) },
	{ new KeyValuePair<int, TokenType>(57, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(62, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(66, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 29) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 28) },
	{ new KeyValuePair<int, TokenType>(69, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 27) },
	{ new KeyValuePair<int, TokenType>(71, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(73, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 32) },
	{ new KeyValuePair<int, TokenType>(75, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 70) },
	{ new KeyValuePair<int, TokenType>(77, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 33) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(82, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 70) },
	{ new KeyValuePair<int, TokenType>(84, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(104, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 105) },
	{ new KeyValuePair<int, TokenType>(115, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 116) },
	{ new KeyValuePair<int, TokenType>(117, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 14) },
	{ new KeyValuePair<int, TokenType>(118, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 13) },
	{ new KeyValuePair<int, TokenType>(119, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 12) },
	{ new KeyValuePair<int, TokenType>(0, TokenType.CLASS), new ParseAction(ParseActionKind.SHIFT, 4) },
	{ new KeyValuePair<int, TokenType>(2, TokenType.EOF), new ParseAction(ParseActionKind.SHIFT, 3) },
	{ new KeyValuePair<int, TokenType>(6, TokenType.EOF), new ParseAction(ParseActionKind.REDUCE, 2) },
	{ new KeyValuePair<int, TokenType>(9, TokenType.EOF), new ParseAction(ParseActionKind.REDUCE, 3) },
	{ new KeyValuePair<int, TokenType>(1, TokenType.EOF), new ParseAction(ParseActionKind.ACCEPT) },
	{ new KeyValuePair<int, TokenType>(3, TokenType.EOF), new ParseAction(ParseActionKind.REDUCE, 1) }
};
        }


        // GOTO DICTIONARY 
        public Dictionary<KeyValuePair<int, string>, int> CreateGoToTable()
        {
            return new Dictionary<KeyValuePair<int, string>, int>()
{
	{ new KeyValuePair<int, string>(0, "PS_PROGRAM"), 1},
	{ new KeyValuePair<int, string>(0, "CLASS_DEF"), 2},
	{ new KeyValuePair<int, string>(5, "CLASS_BODY"), 6},
	{ new KeyValuePair<int, string>(7, "CLASS_DECLARATIONS"), 8},
	{ new KeyValuePair<int, string>(10, "CLASS_DECLARATIONS"), 11},
	{ new KeyValuePair<int, string>(12, "CLASS_DECLARATIONS"), 13},
	{ new KeyValuePair<int, string>(7, "FIELD_DECLARATION"), 12},
	{ new KeyValuePair<int, string>(10, "FIELD_DECLARATION"), 12},
	{ new KeyValuePair<int, string>(12, "FIELD_DECLARATION"), 12},
	{ new KeyValuePair<int, string>(7, "VISIBILITY_MODIFIER"), 102},
	{ new KeyValuePair<int, string>(10, "VISIBILITY_MODIFIER"), 102},
	{ new KeyValuePair<int, string>(12, "VISIBILITY_MODIFIER"), 102},
	{ new KeyValuePair<int, string>(102, "STATIC_MODIFIER"), 103},
	{ new KeyValuePair<int, string>(103, "TYPE_DEFINITION"), 104},
	{ new KeyValuePair<int, string>(108, "TYPE_DEFINITION"), 115},
	{ new KeyValuePair<int, string>(113, "TYPE_DEFINITION"), 115},
	{ new KeyValuePair<int, string>(7, "METHOD_DECLARATION"), 10},
	{ new KeyValuePair<int, string>(10, "METHOD_DECLARATION"), 10},
	{ new KeyValuePair<int, string>(12, "METHOD_DECLARATION"), 10},
	{ new KeyValuePair<int, string>(7, "METHOD_HEADER"), 14},
	{ new KeyValuePair<int, string>(10, "METHOD_HEADER"), 14},
	{ new KeyValuePair<int, string>(12, "METHOD_HEADER"), 14},
	{ new KeyValuePair<int, string>(105, "METHOD_ARGS"), 107},
	{ new KeyValuePair<int, string>(108, "ARGUMENTS_DEFINITION"), 110},
	{ new KeyValuePair<int, string>(113, "ARGUMENTS_DEFINITION"), 114},
	{ new KeyValuePair<int, string>(108, "ARGUMENT_DEFINITION"), 112},
	{ new KeyValuePair<int, string>(113, "ARGUMENT_DEFINITION"), 112},
	{ new KeyValuePair<int, string>(15, "STATEMENTS_BLOCK"), 16},
	{ new KeyValuePair<int, string>(75, "STATEMENTS_BLOCK"), 76},
	{ new KeyValuePair<int, string>(82, "STATEMENTS_BLOCK"), 83},
	{ new KeyValuePair<int, string>(15, "STATEMENTS"), 20},
	{ new KeyValuePair<int, string>(21, "STATEMENTS"), 23},
	{ new KeyValuePair<int, string>(75, "STATEMENTS"), 20},
	{ new KeyValuePair<int, string>(82, "STATEMENTS"), 20},
	{ new KeyValuePair<int, string>(21, "STATEMENTS_S"), 22},
	{ new KeyValuePair<int, string>(15, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(21, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(75, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(82, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(15, "ASSIGN_STATEMENT"), 65},
	{ new KeyValuePair<int, string>(21, "ASSIGN_STATEMENT"), 65},
	{ new KeyValuePair<int, string>(75, "ASSIGN_STATEMENT"), 65},
	{ new KeyValuePair<int, string>(82, "ASSIGN_STATEMENT"), 65},
	{ new KeyValuePair<int, string>(15, "IF_STATEMENT"), 67},
	{ new KeyValuePair<int, string>(21, "IF_STATEMENT"), 67},
	{ new KeyValuePair<int, string>(75, "IF_STATEMENT"), 67},
	{ new KeyValuePair<int, string>(82, "IF_STATEMENT"), 67},
	{ new KeyValuePair<int, string>(15, "IF_THEN_STATEMENT"), 73},
	{ new KeyValuePair<int, string>(21, "IF_THEN_STATEMENT"), 73},
	{ new KeyValuePair<int, string>(75, "IF_THEN_STATEMENT"), 73},
	{ new KeyValuePair<int, string>(82, "IF_THEN_STATEMENT"), 73},
	{ new KeyValuePair<int, string>(24, "EXPRESSION"), 25},
	{ new KeyValuePair<int, string>(46, "EXPRESSION"), 47},
	{ new KeyValuePair<int, string>(57, "EXPRESSION"), 61},
	{ new KeyValuePair<int, string>(62, "EXPRESSION"), 61},
	{ new KeyValuePair<int, string>(71, "EXPRESSION"), 72},
	{ new KeyValuePair<int, string>(79, "EXPRESSION"), 91},
	{ new KeyValuePair<int, string>(86, "EXPRESSION"), 91},
	{ new KeyValuePair<int, string>(89, "EXPRESSION"), 91},
	{ new KeyValuePair<int, string>(93, "EXPRESSION"), 94},
	{ new KeyValuePair<int, string>(100, "EXPRESSION"), 91},
	{ new KeyValuePair<int, string>(29, "EXPRESSION_S"), 30},
	{ new KeyValuePair<int, string>(32, "EXPRESSION_S"), 33},
	{ new KeyValuePair<int, string>(24, "TERM"), 29},
	{ new KeyValuePair<int, string>(31, "TERM"), 32},
	{ new KeyValuePair<int, string>(46, "TERM"), 29},
	{ new KeyValuePair<int, string>(57, "TERM"), 29},
	{ new KeyValuePair<int, string>(62, "TERM"), 29},
	{ new KeyValuePair<int, string>(71, "TERM"), 29},
	{ new KeyValuePair<int, string>(79, "TERM"), 29},
	{ new KeyValuePair<int, string>(86, "TERM"), 29},
	{ new KeyValuePair<int, string>(89, "TERM"), 29},
	{ new KeyValuePair<int, string>(93, "TERM"), 29},
	{ new KeyValuePair<int, string>(100, "TERM"), 29},
	{ new KeyValuePair<int, string>(36, "TERM_S"), 37},
	{ new KeyValuePair<int, string>(39, "TERM_S"), 40},
	{ new KeyValuePair<int, string>(24, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(31, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(38, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(46, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(57, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(62, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(71, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(79, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(86, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(89, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(93, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(100, "SIMPLE_TERM"), 36},
	{ new KeyValuePair<int, string>(29, "FIRST_PREC_OPERATOR"), 31},
	{ new KeyValuePair<int, string>(32, "FIRST_PREC_OPERATOR"), 31},
	{ new KeyValuePair<int, string>(36, "SECOND_PREC_OPERATOR"), 38},
	{ new KeyValuePair<int, string>(39, "SECOND_PREC_OPERATOR"), 38},
	{ new KeyValuePair<int, string>(15, "FUNC_CALL"), 68},
	{ new KeyValuePair<int, string>(21, "FUNC_CALL"), 68},
	{ new KeyValuePair<int, string>(24, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(46, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(57, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(62, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(71, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(75, "FUNC_CALL"), 68},
	{ new KeyValuePair<int, string>(79, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(82, "FUNC_CALL"), 68},
	{ new KeyValuePair<int, string>(86, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(89, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(93, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(100, "FUNC_CALL"), 28},
	{ new KeyValuePair<int, string>(15, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(21, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(24, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(46, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(57, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(62, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(71, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(75, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(79, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(82, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(86, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(89, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(93, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(100, "THIS_METHOD_CALL"), 52},
	{ new KeyValuePair<int, string>(15, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(21, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(24, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(46, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(57, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(62, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(71, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(75, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(79, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(82, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(86, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(89, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(93, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(100, "EXTERNAL_METHOD_CALL"), 51},
	{ new KeyValuePair<int, string>(53, "CALL_ARGS"), 64},
	{ new KeyValuePair<int, string>(55, "CALL_ARGS"), 56},
	{ new KeyValuePair<int, string>(70, "CALL_ARGS"), 64},
	{ new KeyValuePair<int, string>(57, "CALL_ARGS_LIST"), 59},
	{ new KeyValuePair<int, string>(62, "CALL_ARGS_LIST"), 63},
	{ new KeyValuePair<int, string>(24, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(46, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(57, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(62, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(71, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(79, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(86, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(89, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(93, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(100, "BOOL_VALUE"), 27},
	{ new KeyValuePair<int, string>(79, "OR_TEST"), 80},
	{ new KeyValuePair<int, string>(86, "OR_TEST"), 87},
	{ new KeyValuePair<int, string>(79, "AND_TEST"), 85},
	{ new KeyValuePair<int, string>(86, "AND_TEST"), 85},
	{ new KeyValuePair<int, string>(89, "AND_TEST"), 90},
	{ new KeyValuePair<int, string>(79, "NOT_TEST"), 88},
	{ new KeyValuePair<int, string>(86, "NOT_TEST"), 88},
	{ new KeyValuePair<int, string>(89, "NOT_TEST"), 88},
	{ new KeyValuePair<int, string>(100, "NOT_TEST"), 101},
	{ new KeyValuePair<int, string>(91, "COMPARISON_S"), 92},
	{ new KeyValuePair<int, string>(91, "COMPARE_OPERATION"), 93}
};
        }
        
        // PRODUCTIONS 
        public Dictionary<int, ProductionInfo> CreateProductionsInfo()
        {
            return new Dictionary<int, ProductionInfo>()
{
{1, new ProductionInfo("PS_PROGRAM", 2, "ConstructPsProgram")}, // #PS_PROGRAM #CLASS_DEF EOF
{2, new ProductionInfo("CLASS_DEF", 3, "ConstructClass")}, // #CLASS_DEF CLASS ID #CLASS_BODY
{3, new ProductionInfo("CLASS_BODY", 3, "ConstructClassBody")}, // #CLASS_BODY BLOCK_START #CLASS_DECLARATIONS BLOCK_END
{4, new ProductionInfo("CLASS_DECLARATIONS", 2, "ConstructClassFieldDeclarations")}, // #CLASS_DECLARATIONS #FIELD_DECLARATION #CLASS_DECLARATIONS
{5, new ProductionInfo("CLASS_DECLARATIONS", 2, "ConstructClassMethodDeclarations")}, // #CLASS_DECLARATIONS #METHOD_DECLARATION #CLASS_DECLARATIONS
{6, new ProductionInfo("CLASS_DECLARATIONS", 0, "ConstructEmptyClassDeclarations")}, // #CLASS_DECLARATIONS
{7, new ProductionInfo("FIELD_DECLARATION", 5, "ConstructFieldDeclaration")}, // #FIELD_DECLARATION #VISIBILITY_MODIFIER #STATIC_MODIFIER #TYPE_DEFINITION ID LINE_END
{8, new ProductionInfo("VISIBILITY_MODIFIER", 1, "ConstructPublicVisibilityModifier")}, // #VISIBILITY_MODIFIER PUBLIC
{9, new ProductionInfo("VISIBILITY_MODIFIER", 1, "ConstructPrivateVisibilityModifier")}, // #VISIBILITY_MODIFIER PRIVATE
{10, new ProductionInfo("STATIC_MODIFIER", 1, "ConstructStaticModifier")}, // #STATIC_MODIFIER STATIC
{11, new ProductionInfo("STATIC_MODIFIER", 0, "ConstructEmptyStaticModifier")}, // #STATIC_MODIFIER
{12, new ProductionInfo("TYPE_DEFINITION", 1, "ConstructBoolTypeDefinition")}, // #TYPE_DEFINITION BOOL
{13, new ProductionInfo("TYPE_DEFINITION", 1, "ConstructCharTypeDefinition")}, // #TYPE_DEFINITION CHAR
{14, new ProductionInfo("TYPE_DEFINITION", 1, "ConstructIntTypeDefinition")}, // #TYPE_DEFINITION INT
{15, new ProductionInfo("METHOD_DECLARATION", 4, "ConstructMethodDeclaration")}, // #METHOD_DECLARATION #METHOD_HEADER BLOCK_START #STATEMENTS_BLOCK BLOCK_END
{16, new ProductionInfo("METHOD_HEADER", 5, "ConstructMethodHeader")}, // #METHOD_HEADER #VISIBILITY_MODIFIER #STATIC_MODIFIER #TYPE_DEFINITION ID #METHOD_ARGS
{17, new ProductionInfo("METHOD_ARGS", 3, "ConstructMethodArgs")}, // #METHOD_ARGS LEFT_PAREN #ARGUMENTS_DEFINITION RIGHT_PAREN
{18, new ProductionInfo("METHOD_ARGS", 2, "ConstructEmptyMethodArgs")}, // #METHOD_ARGS LEFT_PAREN RIGHT_PAREN
{19, new ProductionInfo("ARGUMENTS_DEFINITION", 1, "ConstructArgumentsDefinition")}, // #ARGUMENTS_DEFINITION #ARGUMENT_DEFINITION
{20, new ProductionInfo("ARGUMENTS_DEFINITION", 3, "ConstructArgumentsDefinition")}, // #ARGUMENTS_DEFINITION #ARGUMENT_DEFINITION COMMA #ARGUMENTS_DEFINITION
{21, new ProductionInfo("ARGUMENT_DEFINITION", 2, "ConstructArgumentDefinition")}, // #ARGUMENT_DEFINITION #TYPE_DEFINITION ID
{22, new ProductionInfo("STATEMENTS_BLOCK", 1, "ConstructStatementsBlock")}, // #STATEMENTS_BLOCK #STATEMENTS
{23, new ProductionInfo("STATEMENTS_BLOCK", 2, "ConstructPassStatementsBlock")}, // #STATEMENTS_BLOCK PASS LINE_END
{24, new ProductionInfo("STATEMENTS", 2, "ConstructStatements")}, // #STATEMENTS #STATEMENT #STATEMENTS_S
{25, new ProductionInfo("STATEMENTS_S", 1, "ConstructStatementsS")}, // #STATEMENTS_S #STATEMENTS
{26, new ProductionInfo("STATEMENTS_S", 0, "ConstructStatementsEmptyS")}, // #STATEMENTS_S
{27, new ProductionInfo("STATEMENT", 2, "ConstructFuncCallStatement")}, // #STATEMENT #FUNC_CALL LINE_END
{28, new ProductionInfo("STATEMENT", 1, "ConstructStatement")}, // #STATEMENT #IF_STATEMENT
{29, new ProductionInfo("STATEMENT", 2, "ConstructStatement")}, // #STATEMENT #ASSIGN_STATEMENT LINE_END
{30, new ProductionInfo("STATEMENT", 3, "ConstructReturnStatement")}, // #STATEMENT RETURN #EXPRESSION LINE_END
{31, new ProductionInfo("ASSIGN_STATEMENT", 3, "ConstructAssignStatement")}, // #ASSIGN_STATEMENT ID ASSIGNMENT #EXPRESSION
{32, new ProductionInfo("IF_STATEMENT", 1, "ConstructIfStatement")}, // #IF_STATEMENT #IF_THEN_STATEMENT
{33, new ProductionInfo("IF_STATEMENT", 5, "ConstructIfElseStatement")}, // #IF_STATEMENT #IF_THEN_STATEMENT ELSE BLOCK_START #STATEMENTS_BLOCK BLOCK_END
{34, new ProductionInfo("IF_THEN_STATEMENT", 7, "ConstructIfThenStatement")}, // #IF_THEN_STATEMENT IF LEFT_PAREN #OR_TEST RIGHT_PAREN BLOCK_START #STATEMENTS_BLOCK BLOCK_END
{35, new ProductionInfo("EXPRESSION", 2, "ConstructTermExpression")}, // #EXPRESSION #TERM #EXPRESSION_S
{36, new ProductionInfo("EXPRESSION", 1, "ConstructFuncCallExpression")}, // #EXPRESSION #FUNC_CALL
{37, new ProductionInfo("EXPRESSION", 1, "ConstructBoolValueExpression")}, // #EXPRESSION #BOOL_VALUE
{38, new ProductionInfo("EXPRESSION_S", 3, "ConstructExpressionS")}, // #EXPRESSION_S #FIRST_PREC_OPERATOR #TERM #EXPRESSION_S
{39, new ProductionInfo("EXPRESSION_S", 0, "ConstructEmptyExpressionS")}, // #EXPRESSION_S
{40, new ProductionInfo("TERM", 2, "ConstructTerm")}, // #TERM #SIMPLE_TERM #TERM_S
{41, new ProductionInfo("TERM_S", 3, "ConstructTermS")}, // #TERM_S #SECOND_PREC_OPERATOR #SIMPLE_TERM #TERM_S
{42, new ProductionInfo("TERM_S", 0, "ConstructEmptyTermS")}, // #TERM_S
{43, new ProductionInfo("SIMPLE_TERM", 3, "ConstructSimpleParenTerm")}, // #SIMPLE_TERM LEFT_PAREN #EXPRESSION RIGHT_PAREN
{44, new ProductionInfo("SIMPLE_TERM", 1, "ConstructSimpleIdTerm")}, // #SIMPLE_TERM ID
{45, new ProductionInfo("SIMPLE_TERM", 1, "ConstructSimpleIntValTerm")}, // #SIMPLE_TERM INTEGER_VALUE
{46, new ProductionInfo("FIRST_PREC_OPERATOR", 1, "ConstructFirstPrecedancePlusOperator")}, // #FIRST_PREC_OPERATOR PLUS
{47, new ProductionInfo("FIRST_PREC_OPERATOR", 1, "ConstructFirstPrecedanceMinusOperator")}, // #FIRST_PREC_OPERATOR MINUS
{48, new ProductionInfo("SECOND_PREC_OPERATOR", 1, "ConstructSecondPrecedanceMulOperator")}, // #SECOND_PREC_OPERATOR MULTIPLICATION
{49, new ProductionInfo("SECOND_PREC_OPERATOR", 1, "ConstructSecondPrecedanceDivOperator")}, // #SECOND_PREC_OPERATOR DIV
{50, new ProductionInfo("SECOND_PREC_OPERATOR", 1, "ConstructSecondPrecedanceModOperator")}, // #SECOND_PREC_OPERATOR MOD
{51, new ProductionInfo("FUNC_CALL", 1, "ConstructFuncCall")}, // #FUNC_CALL #THIS_METHOD_CALL
{52, new ProductionInfo("FUNC_CALL", 1, "ConstructFuncCall")}, // #FUNC_CALL #EXTERNAL_METHOD_CALL
{53, new ProductionInfo("THIS_METHOD_CALL", 2, "ConstructThisMethodCall")}, // #THIS_METHOD_CALL ID #CALL_ARGS
{54, new ProductionInfo("EXTERNAL_METHOD_CALL", 4, "ConstructExternalMethodCall")}, // #EXTERNAL_METHOD_CALL ID DOT ID #CALL_ARGS
{55, new ProductionInfo("CALL_ARGS", 3, "ConstructCallArgs")}, // #CALL_ARGS LEFT_PAREN #CALL_ARGS_LIST RIGHT_PAREN
{56, new ProductionInfo("CALL_ARGS", 2, "ConstructEmptyCallArgs")}, // #CALL_ARGS LEFT_PAREN RIGHT_PAREN
{57, new ProductionInfo("CALL_ARGS_LIST", 1, "ConstructCallArgsList")}, // #CALL_ARGS_LIST #EXPRESSION
{58, new ProductionInfo("CALL_ARGS_LIST", 3, "ConstructCallArgsListAdd")}, // #CALL_ARGS_LIST #EXPRESSION COMMA #CALL_ARGS_LIST
{59, new ProductionInfo("BOOL_VALUE", 1, "ConstructBoolTrueValue")}, // #BOOL_VALUE TRUE
{60, new ProductionInfo("BOOL_VALUE", 1, "ConstructBoolFalseValue")}, // #BOOL_VALUE FALSE
{61, new ProductionInfo("OR_TEST", 1, "ConstructOrTest")}, // #OR_TEST #AND_TEST
{62, new ProductionInfo("OR_TEST", 3, "ConstructOrCompoundTest")}, // #OR_TEST #AND_TEST OR #OR_TEST
{63, new ProductionInfo("AND_TEST", 1, "ConstructAndTest")}, // #AND_TEST #NOT_TEST
{64, new ProductionInfo("AND_TEST", 3, "ConstructAndCompoundTest")}, // #AND_TEST #NOT_TEST AND #AND_TEST
{65, new ProductionInfo("NOT_TEST", 2, "ConstructNotTest")}, // #NOT_TEST NOT #NOT_TEST
{66, new ProductionInfo("NOT_TEST", 2, "ConstructNotCompoundTest")}, // #NOT_TEST #EXPRESSION #COMPARISON_S
{67, new ProductionInfo("COMPARISON_S", 2, "ConstructComparisonS")}, // #COMPARISON_S #COMPARE_OPERATION #EXPRESSION
{68, new ProductionInfo("COMPARISON_S", 0, "ConstructEmptyComparisonS")}, // #COMPARISON_S
{69, new ProductionInfo("COMPARE_OPERATION", 1, "ConstructCompareOperationLt")}, // #COMPARE_OPERATION LT
{70, new ProductionInfo("COMPARE_OPERATION", 1, "ConstructCompareOperationGt")}, // #COMPARE_OPERATION GT
{71, new ProductionInfo("COMPARE_OPERATION", 1, "ConstructCompareOperationGte")}, // #COMPARE_OPERATION GTE
{72, new ProductionInfo("COMPARE_OPERATION", 1, "ConstructCompareOperationLte")}, // #COMPARE_OPERATION LTE
{73, new ProductionInfo("COMPARE_OPERATION", 1, "ConstructCompareOperationEql")} // #COMPARE_OPERATION EQUAL
};
        }
        

    }
}
