using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace compiler
{
    class ParseTableBuilder
    {
        public static ParseTable Build()
        {
            var builder = new ParseTableBuilder();

            var table = new ParseTable();
            table.SetActionsTable(builder.CreateActionsTable());
            table.SetGoToTable(builder.CreateGoToTable());
            table.SetProductionsInfoTable(builder.CreateProductionsInfo());
            return table;
        }

        // PARSE ACTIONS DICTIONARY
        public Dictionary<KeyValuePair<int, TokenType>, ParseAction> CreateActionsTable()
        {
            return new Dictionary<KeyValuePair<int, TokenType>, ParseAction>()
{
	{ new KeyValuePair<int, TokenType>(30, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.EQUAL), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.EQUAL), new ParseAction(ParseActionKind.SHIFT, 92) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.LTE), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.LTE), new ParseAction(ParseActionKind.SHIFT, 93) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.GTE), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.GTE), new ParseAction(ParseActionKind.SHIFT, 94) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.GT), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.GT), new ParseAction(ParseActionKind.SHIFT, 95) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.LT), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.LT), new ParseAction(ParseActionKind.SHIFT, 96) },
	{ new KeyValuePair<int, TokenType>(76, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 97) },
	{ new KeyValuePair<int, TokenType>(83, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 97) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 97) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.NOT), new ParseAction(ParseActionKind.SHIFT, 97) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(85, TokenType.AND), new ParseAction(ParseActionKind.SHIFT, 86) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 68) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 66) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 67) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.AND), new ParseAction(ParseActionKind.REDUCE, 65) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(82, TokenType.OR), new ParseAction(ParseActionKind.SHIFT, 83) },
	{ new KeyValuePair<int, TokenType>(85, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 63) },
	{ new KeyValuePair<int, TokenType>(87, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 64) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 68) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 66) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 67) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.OR), new ParseAction(ParseActionKind.REDUCE, 65) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(65, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(76, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(83, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(90, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.FALSE), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.FALSE), new ParseAction(ParseActionKind.SHIFT, 52) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(65, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(76, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(83, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(90, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.TRUE), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.TRUE), new ParseAction(ParseActionKind.SHIFT, 53) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.DOT), new ParseAction(ParseActionKind.SHIFT, 57) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.DOT), new ParseAction(ParseActionKind.SHIFT, 57) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.MOD), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.MOD), new ParseAction(ParseActionKind.SHIFT, 44) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.MOD), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.DIV), new ParseAction(ParseActionKind.SHIFT, 45) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.DIV), new ParseAction(ParseActionKind.SHIFT, 45) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.DIV), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.SHIFT, 46) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.MULTIPLICATION), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.MINUS), new ParseAction(ParseActionKind.SHIFT, 37) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.MINUS), new ParseAction(ParseActionKind.SHIFT, 37) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.MINUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.PLUS), new ParseAction(ParseActionKind.SHIFT, 38) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.PLUS), new ParseAction(ParseActionKind.SHIFT, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.PLUS), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(34, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 47) },
	{ new KeyValuePair<int, TokenType>(38, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 46) },
	{ new KeyValuePair<int, TokenType>(41, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 50) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 49) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 48) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(65, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(76, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(83, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(90, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.INTEGER_VALUE), new ParseAction(ParseActionKind.SHIFT, 47) },
	{ new KeyValuePair<int, TokenType>(15, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 75) },
	{ new KeyValuePair<int, TokenType>(21, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 75) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 29) },
	{ new KeyValuePair<int, TokenType>(25, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 28) },
	{ new KeyValuePair<int, TokenType>(26, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 27) },
	{ new KeyValuePair<int, TokenType>(68, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 32) },
	{ new KeyValuePair<int, TokenType>(70, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 75) },
	{ new KeyValuePair<int, TokenType>(72, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 33) },
	{ new KeyValuePair<int, TokenType>(74, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 30) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.IF), new ParseAction(ParseActionKind.SHIFT, 75) },
	{ new KeyValuePair<int, TokenType>(81, TokenType.IF), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(68, TokenType.ELSE), new ParseAction(ParseActionKind.SHIFT, 69) },
	{ new KeyValuePair<int, TokenType>(81, TokenType.ELSE), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.ASSIGNMENT), new ParseAction(ParseActionKind.SHIFT, 28) },
	{ new KeyValuePair<int, TokenType>(15, TokenType.PASS), new ParseAction(ParseActionKind.SHIFT, 18) },
	{ new KeyValuePair<int, TokenType>(70, TokenType.PASS), new ParseAction(ParseActionKind.SHIFT, 18) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.PASS), new ParseAction(ParseActionKind.SHIFT, 18) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.COMMA), new ParseAction(ParseActionKind.SHIFT, 65) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(108, TokenType.COMMA), new ParseAction(ParseActionKind.SHIFT, 109) },
	{ new KeyValuePair<int, TokenType>(112, TokenType.COMMA), new ParseAction(ParseActionKind.REDUCE, 22) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(50, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 51) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 61) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(62, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 63) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(64, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 57) },
	{ new KeyValuePair<int, TokenType>(66, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 58) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(77, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 78) },
	{ new KeyValuePair<int, TokenType>(82, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 61) },
	{ new KeyValuePair<int, TokenType>(84, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 62) },
	{ new KeyValuePair<int, TokenType>(85, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 63) },
	{ new KeyValuePair<int, TokenType>(87, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 64) },
	{ new KeyValuePair<int, TokenType>(88, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 68) },
	{ new KeyValuePair<int, TokenType>(89, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 66) },
	{ new KeyValuePair<int, TokenType>(91, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 67) },
	{ new KeyValuePair<int, TokenType>(98, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 65) },
	{ new KeyValuePair<int, TokenType>(104, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 105) },
	{ new KeyValuePair<int, TokenType>(106, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.SHIFT, 107) },
	{ new KeyValuePair<int, TokenType>(108, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 20) },
	{ new KeyValuePair<int, TokenType>(110, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 21) },
	{ new KeyValuePair<int, TokenType>(112, TokenType.RIGHT_PAREN), new ParseAction(ParseActionKind.REDUCE, 22) },
	{ new KeyValuePair<int, TokenType>(27, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 60) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(34, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 47) },
	{ new KeyValuePair<int, TokenType>(38, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 46) },
	{ new KeyValuePair<int, TokenType>(41, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 50) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 49) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 48) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 60) },
	{ new KeyValuePair<int, TokenType>(58, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 60) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(65, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(75, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 76) },
	{ new KeyValuePair<int, TokenType>(76, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(83, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(90, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 49) },
	{ new KeyValuePair<int, TokenType>(102, TokenType.LEFT_PAREN), new ParseAction(ParseActionKind.SHIFT, 104) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.INT), new ParseAction(ParseActionKind.SHIFT, 113) },
	{ new KeyValuePair<int, TokenType>(104, TokenType.INT), new ParseAction(ParseActionKind.SHIFT, 113) },
	{ new KeyValuePair<int, TokenType>(109, TokenType.INT), new ParseAction(ParseActionKind.SHIFT, 113) },
	{ new KeyValuePair<int, TokenType>(116, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 9) },
	{ new KeyValuePair<int, TokenType>(117, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(118, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 7) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.INT), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(123, TokenType.INT), new ParseAction(ParseActionKind.SHIFT, 113) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.CHAR), new ParseAction(ParseActionKind.SHIFT, 114) },
	{ new KeyValuePair<int, TokenType>(104, TokenType.CHAR), new ParseAction(ParseActionKind.SHIFT, 114) },
	{ new KeyValuePair<int, TokenType>(109, TokenType.CHAR), new ParseAction(ParseActionKind.SHIFT, 114) },
	{ new KeyValuePair<int, TokenType>(116, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 9) },
	{ new KeyValuePair<int, TokenType>(117, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(118, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 7) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.CHAR), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(123, TokenType.CHAR), new ParseAction(ParseActionKind.SHIFT, 114) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(100, TokenType.BOOL), new ParseAction(ParseActionKind.SHIFT, 115) },
	{ new KeyValuePair<int, TokenType>(104, TokenType.BOOL), new ParseAction(ParseActionKind.SHIFT, 115) },
	{ new KeyValuePair<int, TokenType>(109, TokenType.BOOL), new ParseAction(ParseActionKind.SHIFT, 115) },
	{ new KeyValuePair<int, TokenType>(116, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 9) },
	{ new KeyValuePair<int, TokenType>(117, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(118, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 7) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.BOOL), new ParseAction(ParseActionKind.REDUCE, 10) },
	{ new KeyValuePair<int, TokenType>(123, TokenType.BOOL), new ParseAction(ParseActionKind.SHIFT, 115) },
	{ new KeyValuePair<int, TokenType>(99, TokenType.STATIC), new ParseAction(ParseActionKind.SHIFT, 116) },
	{ new KeyValuePair<int, TokenType>(117, TokenType.STATIC), new ParseAction(ParseActionKind.REDUCE, 8) },
	{ new KeyValuePair<int, TokenType>(118, TokenType.STATIC), new ParseAction(ParseActionKind.REDUCE, 7) },
	{ new KeyValuePair<int, TokenType>(122, TokenType.STATIC), new ParseAction(ParseActionKind.SHIFT, 116) },
	{ new KeyValuePair<int, TokenType>(6, TokenType.PRIVATE), new ParseAction(ParseActionKind.SHIFT, 117) },
	{ new KeyValuePair<int, TokenType>(8, TokenType.PRIVATE), new ParseAction(ParseActionKind.SHIFT, 117) },
	{ new KeyValuePair<int, TokenType>(12, TokenType.PRIVATE), new ParseAction(ParseActionKind.SHIFT, 117) },
	{ new KeyValuePair<int, TokenType>(120, TokenType.PRIVATE), new ParseAction(ParseActionKind.SHIFT, 117) },
	{ new KeyValuePair<int, TokenType>(6, TokenType.PUBLIC), new ParseAction(ParseActionKind.SHIFT, 118) },
	{ new KeyValuePair<int, TokenType>(8, TokenType.PUBLIC), new ParseAction(ParseActionKind.SHIFT, 118) },
	{ new KeyValuePair<int, TokenType>(12, TokenType.PUBLIC), new ParseAction(ParseActionKind.SHIFT, 118) },
	{ new KeyValuePair<int, TokenType>(120, TokenType.PUBLIC), new ParseAction(ParseActionKind.SHIFT, 118) },
	{ new KeyValuePair<int, TokenType>(9, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 10) },
	{ new KeyValuePair<int, TokenType>(12, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 14) },
	{ new KeyValuePair<int, TokenType>(13, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 15) },
	{ new KeyValuePair<int, TokenType>(16, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 17) },
	{ new KeyValuePair<int, TokenType>(19, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 24) },
	{ new KeyValuePair<int, TokenType>(20, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 23) },
	{ new KeyValuePair<int, TokenType>(21, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 25) },
	{ new KeyValuePair<int, TokenType>(22, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 26) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 29) },
	{ new KeyValuePair<int, TokenType>(25, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 28) },
	{ new KeyValuePair<int, TokenType>(26, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 27) },
	{ new KeyValuePair<int, TokenType>(68, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 32) },
	{ new KeyValuePair<int, TokenType>(71, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 72) },
	{ new KeyValuePair<int, TokenType>(72, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 33) },
	{ new KeyValuePair<int, TokenType>(74, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 30) },
	{ new KeyValuePair<int, TokenType>(80, TokenType.BLOCK_END), new ParseAction(ParseActionKind.SHIFT, 81) },
	{ new KeyValuePair<int, TokenType>(81, TokenType.BLOCK_END), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(7, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 8) },
	{ new KeyValuePair<int, TokenType>(11, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 12) },
	{ new KeyValuePair<int, TokenType>(17, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 16) },
	{ new KeyValuePair<int, TokenType>(18, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 19) },
	{ new KeyValuePair<int, TokenType>(23, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 24) },
	{ new KeyValuePair<int, TokenType>(29, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 31) },
	{ new KeyValuePair<int, TokenType>(30, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 37) },
	{ new KeyValuePair<int, TokenType>(31, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 36) },
	{ new KeyValuePair<int, TokenType>(32, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(33, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 35) },
	{ new KeyValuePair<int, TokenType>(35, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 39) },
	{ new KeyValuePair<int, TokenType>(36, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 38) },
	{ new KeyValuePair<int, TokenType>(39, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(40, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 40) },
	{ new KeyValuePair<int, TokenType>(42, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 42) },
	{ new KeyValuePair<int, TokenType>(43, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 41) },
	{ new KeyValuePair<int, TokenType>(47, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 45) },
	{ new KeyValuePair<int, TokenType>(48, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(51, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 43) },
	{ new KeyValuePair<int, TokenType>(52, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 60) },
	{ new KeyValuePair<int, TokenType>(53, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 59) },
	{ new KeyValuePair<int, TokenType>(54, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 52) },
	{ new KeyValuePair<int, TokenType>(55, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 51) },
	{ new KeyValuePair<int, TokenType>(56, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 44) },
	{ new KeyValuePair<int, TokenType>(59, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 54) },
	{ new KeyValuePair<int, TokenType>(61, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 56) },
	{ new KeyValuePair<int, TokenType>(63, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 55) },
	{ new KeyValuePair<int, TokenType>(67, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 53) },
	{ new KeyValuePair<int, TokenType>(73, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 74) },
	{ new KeyValuePair<int, TokenType>(119, TokenType.LINE_END), new ParseAction(ParseActionKind.SHIFT, 120) },
	{ new KeyValuePair<int, TokenType>(120, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 4) },
	{ new KeyValuePair<int, TokenType>(121, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 5) },
	{ new KeyValuePair<int, TokenType>(125, TokenType.LINE_END), new ParseAction(ParseActionKind.REDUCE, 6) },
	{ new KeyValuePair<int, TokenType>(4, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 6) },
	{ new KeyValuePair<int, TokenType>(14, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 15) },
	{ new KeyValuePair<int, TokenType>(69, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 70) },
	{ new KeyValuePair<int, TokenType>(78, TokenType.BLOCK_START), new ParseAction(ParseActionKind.SHIFT, 79) },
	{ new KeyValuePair<int, TokenType>(103, TokenType.BLOCK_START), new ParseAction(ParseActionKind.REDUCE, 17) },
	{ new KeyValuePair<int, TokenType>(105, TokenType.BLOCK_START), new ParseAction(ParseActionKind.REDUCE, 19) },
	{ new KeyValuePair<int, TokenType>(107, TokenType.BLOCK_START), new ParseAction(ParseActionKind.REDUCE, 18) },
	{ new KeyValuePair<int, TokenType>(3, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 4) },
	{ new KeyValuePair<int, TokenType>(15, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 27) },
	{ new KeyValuePair<int, TokenType>(21, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 27) },
	{ new KeyValuePair<int, TokenType>(24, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 29) },
	{ new KeyValuePair<int, TokenType>(25, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 28) },
	{ new KeyValuePair<int, TokenType>(26, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 27) },
	{ new KeyValuePair<int, TokenType>(28, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(34, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 48) },
	{ new KeyValuePair<int, TokenType>(37, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 47) },
	{ new KeyValuePair<int, TokenType>(38, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 46) },
	{ new KeyValuePair<int, TokenType>(41, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 48) },
	{ new KeyValuePair<int, TokenType>(44, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 50) },
	{ new KeyValuePair<int, TokenType>(45, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 49) },
	{ new KeyValuePair<int, TokenType>(46, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 48) },
	{ new KeyValuePair<int, TokenType>(49, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(57, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 58) },
	{ new KeyValuePair<int, TokenType>(60, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(65, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(68, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 32) },
	{ new KeyValuePair<int, TokenType>(70, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 27) },
	{ new KeyValuePair<int, TokenType>(72, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 33) },
	{ new KeyValuePair<int, TokenType>(74, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 30) },
	{ new KeyValuePair<int, TokenType>(76, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(79, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 27) },
	{ new KeyValuePair<int, TokenType>(81, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 34) },
	{ new KeyValuePair<int, TokenType>(83, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(86, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(90, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(92, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 73) },
	{ new KeyValuePair<int, TokenType>(93, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 72) },
	{ new KeyValuePair<int, TokenType>(94, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 71) },
	{ new KeyValuePair<int, TokenType>(95, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 70) },
	{ new KeyValuePair<int, TokenType>(96, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 69) },
	{ new KeyValuePair<int, TokenType>(97, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 56) },
	{ new KeyValuePair<int, TokenType>(101, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 102) },
	{ new KeyValuePair<int, TokenType>(111, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 112) },
	{ new KeyValuePair<int, TokenType>(113, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 13) },
	{ new KeyValuePair<int, TokenType>(114, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 12) },
	{ new KeyValuePair<int, TokenType>(115, TokenType.ID), new ParseAction(ParseActionKind.REDUCE, 11) },
	{ new KeyValuePair<int, TokenType>(124, TokenType.ID), new ParseAction(ParseActionKind.SHIFT, 125) },
	{ new KeyValuePair<int, TokenType>(0, TokenType.CLASS), new ParseAction(ParseActionKind.SHIFT, 3) },
	{ new KeyValuePair<int, TokenType>(1, TokenType.EOF), new ParseAction(ParseActionKind.ACCEPT) },
	{ new KeyValuePair<int, TokenType>(2, TokenType.EOF), new ParseAction(ParseActionKind.REDUCE, 1) },
	{ new KeyValuePair<int, TokenType>(5, TokenType.EOF), new ParseAction(ParseActionKind.REDUCE, 2) },
	{ new KeyValuePair<int, TokenType>(10, TokenType.EOF), new ParseAction(ParseActionKind.REDUCE, 3) }
};
        }


        // GOTO DICTIONARY 
        public Dictionary<KeyValuePair<int, string>, int> CreateGoToTable()
        {
            return new Dictionary<KeyValuePair<int, string>, int>()
{
	{ new KeyValuePair<int, string>(0, "PS_PROGRAM"), 1},
	{ new KeyValuePair<int, string>(0, "CLASS_DEF"), 2},
	{ new KeyValuePair<int, string>(4, "CLASS_BODY"), 5},
	{ new KeyValuePair<int, string>(6, "FIELD_DECLARATIONS"), 7},
	{ new KeyValuePair<int, string>(120, "FIELD_DECLARATIONS"), 121},
	{ new KeyValuePair<int, string>(6, "FIELD_DECLARATION"), 119},
	{ new KeyValuePair<int, string>(120, "FIELD_DECLARATION"), 119},
	{ new KeyValuePair<int, string>(6, "VISIBILITY_MODIFIER"), 122},
	{ new KeyValuePair<int, string>(8, "VISIBILITY_MODIFIER"), 99},
	{ new KeyValuePair<int, string>(12, "VISIBILITY_MODIFIER"), 99},
	{ new KeyValuePair<int, string>(120, "VISIBILITY_MODIFIER"), 122},
	{ new KeyValuePair<int, string>(99, "STATIC_MODIFIER"), 100},
	{ new KeyValuePair<int, string>(122, "STATIC_MODIFIER"), 123},
	{ new KeyValuePair<int, string>(100, "TYPE_DEFINITION"), 101},
	{ new KeyValuePair<int, string>(104, "TYPE_DEFINITION"), 111},
	{ new KeyValuePair<int, string>(109, "TYPE_DEFINITION"), 111},
	{ new KeyValuePair<int, string>(123, "TYPE_DEFINITION"), 124},
	{ new KeyValuePair<int, string>(8, "METHOD_DECLARATIONS"), 9},
	{ new KeyValuePair<int, string>(12, "METHOD_DECLARATIONS"), 13},
	{ new KeyValuePair<int, string>(8, "METHOD_DECLARATION"), 11},
	{ new KeyValuePair<int, string>(12, "METHOD_DECLARATION"), 11},
	{ new KeyValuePair<int, string>(8, "METHOD_HEADER"), 14},
	{ new KeyValuePair<int, string>(12, "METHOD_HEADER"), 14},
	{ new KeyValuePair<int, string>(102, "METHOD_ARGS"), 103},
	{ new KeyValuePair<int, string>(104, "ARGUMENTS_DEFINITION"), 106},
	{ new KeyValuePair<int, string>(109, "ARGUMENTS_DEFINITION"), 110},
	{ new KeyValuePair<int, string>(104, "ARGUMENT_DEFINITION"), 108},
	{ new KeyValuePair<int, string>(109, "ARGUMENT_DEFINITION"), 108},
	{ new KeyValuePair<int, string>(15, "STATEMENTS_BLOCK"), 16},
	{ new KeyValuePair<int, string>(70, "STATEMENTS_BLOCK"), 71},
	{ new KeyValuePair<int, string>(79, "STATEMENTS_BLOCK"), 80},
	{ new KeyValuePair<int, string>(15, "STATEMENTS"), 20},
	{ new KeyValuePair<int, string>(21, "STATEMENTS"), 22},
	{ new KeyValuePair<int, string>(70, "STATEMENTS"), 20},
	{ new KeyValuePair<int, string>(79, "STATEMENTS"), 20},
	{ new KeyValuePair<int, string>(15, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(21, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(70, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(79, "STATEMENT"), 21},
	{ new KeyValuePair<int, string>(15, "EXPRESSION_STATEMENT"), 26},
	{ new KeyValuePair<int, string>(21, "EXPRESSION_STATEMENT"), 26},
	{ new KeyValuePair<int, string>(70, "EXPRESSION_STATEMENT"), 26},
	{ new KeyValuePair<int, string>(79, "EXPRESSION_STATEMENT"), 26},
	{ new KeyValuePair<int, string>(15, "ASSIGN_STATEMENT"), 23},
	{ new KeyValuePair<int, string>(21, "ASSIGN_STATEMENT"), 23},
	{ new KeyValuePair<int, string>(70, "ASSIGN_STATEMENT"), 23},
	{ new KeyValuePair<int, string>(79, "ASSIGN_STATEMENT"), 23},
	{ new KeyValuePair<int, string>(15, "IF_STATEMENT"), 25},
	{ new KeyValuePair<int, string>(21, "IF_STATEMENT"), 25},
	{ new KeyValuePair<int, string>(70, "IF_STATEMENT"), 25},
	{ new KeyValuePair<int, string>(79, "IF_STATEMENT"), 25},
	{ new KeyValuePair<int, string>(15, "IF_THEN_STATEMENT"), 68},
	{ new KeyValuePair<int, string>(21, "IF_THEN_STATEMENT"), 68},
	{ new KeyValuePair<int, string>(70, "IF_THEN_STATEMENT"), 68},
	{ new KeyValuePair<int, string>(79, "IF_THEN_STATEMENT"), 68},
	{ new KeyValuePair<int, string>(28, "EXPRESSION"), 29},
	{ new KeyValuePair<int, string>(49, "EXPRESSION"), 50},
	{ new KeyValuePair<int, string>(60, "EXPRESSION"), 64},
	{ new KeyValuePair<int, string>(65, "EXPRESSION"), 64},
	{ new KeyValuePair<int, string>(76, "EXPRESSION"), 88},
	{ new KeyValuePair<int, string>(83, "EXPRESSION"), 88},
	{ new KeyValuePair<int, string>(86, "EXPRESSION"), 88},
	{ new KeyValuePair<int, string>(90, "EXPRESSION"), 91},
	{ new KeyValuePair<int, string>(97, "EXPRESSION"), 88},
	{ new KeyValuePair<int, string>(32, "EXPRESSION_S"), 33},
	{ new KeyValuePair<int, string>(35, "EXPRESSION_S"), 36},
	{ new KeyValuePair<int, string>(28, "TERM"), 32},
	{ new KeyValuePair<int, string>(34, "TERM"), 35},
	{ new KeyValuePair<int, string>(49, "TERM"), 32},
	{ new KeyValuePair<int, string>(60, "TERM"), 32},
	{ new KeyValuePair<int, string>(65, "TERM"), 32},
	{ new KeyValuePair<int, string>(76, "TERM"), 32},
	{ new KeyValuePair<int, string>(83, "TERM"), 32},
	{ new KeyValuePair<int, string>(86, "TERM"), 32},
	{ new KeyValuePair<int, string>(90, "TERM"), 32},
	{ new KeyValuePair<int, string>(97, "TERM"), 32},
	{ new KeyValuePair<int, string>(39, "TERM_S"), 40},
	{ new KeyValuePair<int, string>(42, "TERM_S"), 43},
	{ new KeyValuePair<int, string>(28, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(34, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(41, "SIMPLE_TERM"), 42},
	{ new KeyValuePair<int, string>(49, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(60, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(65, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(76, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(83, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(86, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(90, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(97, "SIMPLE_TERM"), 39},
	{ new KeyValuePair<int, string>(32, "FIRST_PREC_OPERATOR"), 34},
	{ new KeyValuePair<int, string>(35, "FIRST_PREC_OPERATOR"), 34},
	{ new KeyValuePair<int, string>(39, "SECOND_PREC_OPERATOR"), 41},
	{ new KeyValuePair<int, string>(42, "SECOND_PREC_OPERATOR"), 41},
	{ new KeyValuePair<int, string>(15, "FUNC_CALL"), 73},
	{ new KeyValuePair<int, string>(21, "FUNC_CALL"), 73},
	{ new KeyValuePair<int, string>(28, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(49, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(60, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(65, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(70, "FUNC_CALL"), 73},
	{ new KeyValuePair<int, string>(76, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(79, "FUNC_CALL"), 73},
	{ new KeyValuePair<int, string>(83, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(86, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(90, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(97, "FUNC_CALL"), 31},
	{ new KeyValuePair<int, string>(15, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(21, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(28, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(49, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(60, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(65, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(70, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(76, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(79, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(83, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(86, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(90, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(97, "THIS_METHOD_CALL"), 55},
	{ new KeyValuePair<int, string>(15, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(21, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(28, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(49, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(60, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(65, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(70, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(76, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(79, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(83, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(86, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(90, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(97, "EXTERNAL_METHOD_CALL"), 54},
	{ new KeyValuePair<int, string>(27, "CALL_ARGS"), 67},
	{ new KeyValuePair<int, string>(56, "CALL_ARGS"), 67},
	{ new KeyValuePair<int, string>(58, "CALL_ARGS"), 59},
	{ new KeyValuePair<int, string>(60, "CALL_ARGS_LIST"), 62},
	{ new KeyValuePair<int, string>(65, "CALL_ARGS_LIST"), 66},
	{ new KeyValuePair<int, string>(28, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(49, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(60, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(65, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(76, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(83, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(86, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(90, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(97, "BOOL_VALUE"), 30},
	{ new KeyValuePair<int, string>(76, "OR_TEST"), 77},
	{ new KeyValuePair<int, string>(83, "OR_TEST"), 84},
	{ new KeyValuePair<int, string>(76, "AND_TEST"), 82},
	{ new KeyValuePair<int, string>(83, "AND_TEST"), 82},
	{ new KeyValuePair<int, string>(86, "AND_TEST"), 87},
	{ new KeyValuePair<int, string>(76, "NOT_TEST"), 85},
	{ new KeyValuePair<int, string>(83, "NOT_TEST"), 85},
	{ new KeyValuePair<int, string>(86, "NOT_TEST"), 85},
	{ new KeyValuePair<int, string>(97, "NOT_TEST"), 98},
	{ new KeyValuePair<int, string>(88, "COMPARISON_S"), 89},
	{ new KeyValuePair<int, string>(88, "COMPARE_OPERATION"), 90}
};
        }


        // PRODUCTIONS 
        public Dictionary<int, ProductionInfo> CreateProductionsInfo()
        {
            return new Dictionary<int, ProductionInfo>()
{
{1, new ProductionInfo("PS_PROGRAM", 1, "")}, // #PS_PROGRAM #CLASS_DEF
{2, new ProductionInfo("CLASS_DEF", 3, "")}, // #CLASS_DEF CLASS ID #CLASS_BODY
{3, new ProductionInfo("CLASS_BODY", 5, "")}, // #CLASS_BODY BLOCK_START #FIELD_DECLARATIONS LINE_END #METHOD_DECLARATIONS BLOCK_END
{4, new ProductionInfo("FIELD_DECLARATIONS", 2, "")}, // #FIELD_DECLARATIONS #FIELD_DECLARATION LINE_END
{5, new ProductionInfo("FIELD_DECLARATIONS", 3, "")}, // #FIELD_DECLARATIONS #FIELD_DECLARATION LINE_END #FIELD_DECLARATIONS
{6, new ProductionInfo("FIELD_DECLARATION", 4, "")}, // #FIELD_DECLARATION #VISIBILITY_MODIFIER #STATIC_MODIFIER #TYPE_DEFINITION ID
{7, new ProductionInfo("VISIBILITY_MODIFIER", 1, "")}, // #VISIBILITY_MODIFIER PUBLIC
{8, new ProductionInfo("VISIBILITY_MODIFIER", 1, "")}, // #VISIBILITY_MODIFIER PRIVATE
{9, new ProductionInfo("STATIC_MODIFIER", 1, "")}, // #STATIC_MODIFIER STATIC
{10, new ProductionInfo("STATIC_MODIFIER", 0, "")}, // #STATIC_MODIFIER
{11, new ProductionInfo("TYPE_DEFINITION", 1, "")}, // #TYPE_DEFINITION BOOL
{12, new ProductionInfo("TYPE_DEFINITION", 1, "")}, // #TYPE_DEFINITION CHAR
{13, new ProductionInfo("TYPE_DEFINITION", 1, "")}, // #TYPE_DEFINITION INT
{14, new ProductionInfo("METHOD_DECLARATIONS", 2, "")}, // #METHOD_DECLARATIONS #METHOD_DECLARATION LINE_END
{15, new ProductionInfo("METHOD_DECLARATIONS", 3, "")}, // #METHOD_DECLARATIONS #METHOD_DECLARATION LINE_END #METHOD_DECLARATIONS
{16, new ProductionInfo("METHOD_DECLARATION", 4, "")}, // #METHOD_DECLARATION #METHOD_HEADER BLOCK_START #STATEMENTS_BLOCK BLOCK_END
{17, new ProductionInfo("METHOD_HEADER", 5, "")}, // #METHOD_HEADER #VISIBILITY_MODIFIER #STATIC_MODIFIER #TYPE_DEFINITION ID #METHOD_ARGS
{18, new ProductionInfo("METHOD_ARGS", 3, "")}, // #METHOD_ARGS LEFT_PAREN #ARGUMENTS_DEFINITION RIGHT_PAREN
{19, new ProductionInfo("METHOD_ARGS", 2, "")}, // #METHOD_ARGS LEFT_PAREN RIGHT_PAREN
{20, new ProductionInfo("ARGUMENTS_DEFINITION", 1, "")}, // #ARGUMENTS_DEFINITION #ARGUMENT_DEFINITION
{21, new ProductionInfo("ARGUMENTS_DEFINITION", 3, "")}, // #ARGUMENTS_DEFINITION #ARGUMENT_DEFINITION COMMA #ARGUMENTS_DEFINITION
{22, new ProductionInfo("ARGUMENT_DEFINITION", 2, "")}, // #ARGUMENT_DEFINITION #TYPE_DEFINITION ID
{23, new ProductionInfo("STATEMENTS_BLOCK", 1, "")}, // #STATEMENTS_BLOCK #STATEMENTS
{24, new ProductionInfo("STATEMENTS_BLOCK", 2, "")}, // #STATEMENTS_BLOCK PASS LINE_END
{25, new ProductionInfo("STATEMENTS", 1, "")}, // #STATEMENTS #STATEMENT
{26, new ProductionInfo("STATEMENTS", 2, "")}, // #STATEMENTS #STATEMENT #STATEMENTS
{27, new ProductionInfo("STATEMENT", 1, "")}, // #STATEMENT #EXPRESSION_STATEMENT
{28, new ProductionInfo("STATEMENT", 1, "")}, // #STATEMENT #IF_STATEMENT
{29, new ProductionInfo("STATEMENT", 2, "")}, // #STATEMENT #ASSIGN_STATEMENT LINE_END
{30, new ProductionInfo("EXPRESSION_STATEMENT", 2, "")}, // #EXPRESSION_STATEMENT #FUNC_CALL LINE_END
{31, new ProductionInfo("ASSIGN_STATEMENT", 3, "")}, // #ASSIGN_STATEMENT ID ASSIGNMENT #EXPRESSION
{32, new ProductionInfo("IF_STATEMENT", 1, "")}, // #IF_STATEMENT #IF_THEN_STATEMENT
{33, new ProductionInfo("IF_STATEMENT", 5, "")}, // #IF_STATEMENT #IF_THEN_STATEMENT ELSE BLOCK_START #STATEMENTS_BLOCK BLOCK_END
{34, new ProductionInfo("IF_THEN_STATEMENT", 7, "")}, // #IF_THEN_STATEMENT IF LEFT_PAREN #OR_TEST RIGHT_PAREN BLOCK_START #STATEMENTS_BLOCK BLOCK_END
{35, new ProductionInfo("EXPRESSION", 2, "")}, // #EXPRESSION #TERM #EXPRESSION_S
{36, new ProductionInfo("EXPRESSION", 1, "")}, // #EXPRESSION #FUNC_CALL
{37, new ProductionInfo("EXPRESSION", 1, "")}, // #EXPRESSION #BOOL_VALUE
{38, new ProductionInfo("EXPRESSION_S", 3, "")}, // #EXPRESSION_S #FIRST_PREC_OPERATOR #TERM #EXPRESSION_S
{39, new ProductionInfo("EXPRESSION_S", 0, "")}, // #EXPRESSION_S
{40, new ProductionInfo("TERM", 2, "")}, // #TERM #SIMPLE_TERM #TERM_S
{41, new ProductionInfo("TERM_S", 3, "")}, // #TERM_S #SECOND_PREC_OPERATOR #SIMPLE_TERM #TERM_S
{42, new ProductionInfo("TERM_S", 0, "")}, // #TERM_S
{43, new ProductionInfo("SIMPLE_TERM", 3, "")}, // #SIMPLE_TERM LEFT_PAREN #EXPRESSION RIGHT_PAREN
{44, new ProductionInfo("SIMPLE_TERM", 1, "")}, // #SIMPLE_TERM ID
{45, new ProductionInfo("SIMPLE_TERM", 1, "")}, // #SIMPLE_TERM INTEGER_VALUE
{46, new ProductionInfo("FIRST_PREC_OPERATOR", 1, "")}, // #FIRST_PREC_OPERATOR PLUS
{47, new ProductionInfo("FIRST_PREC_OPERATOR", 1, "")}, // #FIRST_PREC_OPERATOR MINUS
{48, new ProductionInfo("SECOND_PREC_OPERATOR", 1, "")}, // #SECOND_PREC_OPERATOR MULTIPLICATION
{49, new ProductionInfo("SECOND_PREC_OPERATOR", 1, "")}, // #SECOND_PREC_OPERATOR DIV
{50, new ProductionInfo("SECOND_PREC_OPERATOR", 1, "")}, // #SECOND_PREC_OPERATOR MOD
{51, new ProductionInfo("FUNC_CALL", 1, "")}, // #FUNC_CALL #THIS_METHOD_CALL
{52, new ProductionInfo("FUNC_CALL", 1, "")}, // #FUNC_CALL #EXTERNAL_METHOD_CALL
{53, new ProductionInfo("THIS_METHOD_CALL", 2, "")}, // #THIS_METHOD_CALL ID #CALL_ARGS
{54, new ProductionInfo("EXTERNAL_METHOD_CALL", 4, "")}, // #EXTERNAL_METHOD_CALL ID DOT ID #CALL_ARGS
{55, new ProductionInfo("CALL_ARGS", 3, "")}, // #CALL_ARGS LEFT_PAREN #CALL_ARGS_LIST RIGHT_PAREN
{56, new ProductionInfo("CALL_ARGS", 2, "")}, // #CALL_ARGS LEFT_PAREN RIGHT_PAREN
{57, new ProductionInfo("CALL_ARGS_LIST", 1, "")}, // #CALL_ARGS_LIST #EXPRESSION
{58, new ProductionInfo("CALL_ARGS_LIST", 3, "")}, // #CALL_ARGS_LIST #EXPRESSION COMMA #CALL_ARGS_LIST
{59, new ProductionInfo("BOOL_VALUE", 1, "")}, // #BOOL_VALUE TRUE
{60, new ProductionInfo("BOOL_VALUE", 1, "")}, // #BOOL_VALUE FALSE
{61, new ProductionInfo("OR_TEST", 1, "")}, // #OR_TEST #AND_TEST
{62, new ProductionInfo("OR_TEST", 3, "")}, // #OR_TEST #AND_TEST OR #OR_TEST
{63, new ProductionInfo("AND_TEST", 1, "")}, // #AND_TEST #NOT_TEST
{64, new ProductionInfo("AND_TEST", 3, "")}, // #AND_TEST #NOT_TEST AND #AND_TEST
{65, new ProductionInfo("NOT_TEST", 2, "")}, // #NOT_TEST NOT #NOT_TEST
{66, new ProductionInfo("NOT_TEST", 2, "")}, // #NOT_TEST #EXPRESSION #COMPARISON_S
{67, new ProductionInfo("COMPARISON_S", 2, "")}, // #COMPARISON_S #COMPARE_OPERATION #EXPRESSION
{68, new ProductionInfo("COMPARISON_S", 0, "")}, // #COMPARISON_S
{69, new ProductionInfo("COMPARE_OPERATION", 1, "")}, // #COMPARE_OPERATION LT
{70, new ProductionInfo("COMPARE_OPERATION", 1, "")}, // #COMPARE_OPERATION GT
{71, new ProductionInfo("COMPARE_OPERATION", 1, "")}, // #COMPARE_OPERATION GTE
{72, new ProductionInfo("COMPARE_OPERATION", 1, "")}, // #COMPARE_OPERATION LTE
{73, new ProductionInfo("COMPARE_OPERATION", 1, "")} // #COMPARE_OPERATION EQUAL
};
        }



    }
}
